all:
  children:
    control_plane:
      hosts:
        ehv2-prod-k8s-0001:
          ansible_host: 192.168.106.201
          # TODO: Find a way to template this
    workers:
      hosts:
        ehv2-prod-k8s-0002:
          ansible_host: 192.168.106.202
        ehv2-prod-k8s-0003:
          ansible_host: 192.168.106.203
  vars:
    ansible_user: user
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'